# Site settings
theme: minima
title: Petar Tasev
email: general@petartasev.com
description: > # this means to ignore newlines until "baseurl:"
  I am a computer engineer based in Southern California.
  My main interests are programming, gaming, and playing basketball.
  At this point, this website serves no purpose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.petartasev.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ptasev

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
